### ISSUE TITLE
how to run the case using frama-c-gui

### ISSUE THREAD

**Issue by aogrcs** [Frama-C/open-source-case-studies#1]
Hi, I make in the sub directory for example libmodbus, then I get the results by command line,, how could I get results using gui? Thanks
Sincerely

**Comment by maroneze** [comment]
Inside the `libmodbus` directory (this also works for the other subdirectories), if you do

    make help

You will get the name of the target(s) for that case study:

    targets: libmodbus-random-test-client

You just need to add the `.eva.gui` suffix to open the results on the GUI:

    make libmodbus-random-test-client.eva.gui

This will run the analysis if necessary, and open the GUI with the results. Note that, unfortunately, tab-completion in the shell will *not* display this target (it is generated in a way that the shell is not able to automatically discover), so if you just do `make <Tab>`, it won't show up. You have to know it exists, as mentioned in the main `README.md` in this repository.

By the way, when you run the `.eva.gui` target, it outputs the actual command line used by the make target:

    frama-c-gui  -load libmodbus-random-test-client.eva/framac.sav

So it's a simple `-load` of the `.sav` file created by the `libmodbus-random-test-client.eva` target, which is the default target of the `GNUmakefile` in that directory.

Just as a reminder, `libmodbus` is not a finished case study, so there is plenty of room for improvements.

**Comment by aogrcs** [comment]
Thanks, maroneze, it did work now
